# Windows
python main_finetune.py --dataset "ecg-TCH-40_patient-20220201" --data_dir "D:\\Dropbox\\Study\\GitHub\\adios\\data" --max_epochs 2 --gpus 0 --precision 32 --optimizer sgd --scheduler warmup_cosine --lr 0.5 --weight_decay 5e-4 --batch_size 256 --num_workers 4 --name "finetune_resnet18_ECG_debug" --project "adios_ecg_debug" --entity "yilongju" --wandb True --ptl_accelerator "cpu" --debug True

# MacOS
python main_finetune.py --seed 0 --encoder "resnet1d" --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "finetune_resnet18_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --transforms "SelectedAug_20221029" --seed 0 --encoder "resnet1d" --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 3 --precision 32 --optimizer sgd --scheduler warmup_cosine --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "finetune_resnet18_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 256 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 4 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

python main_finetune.py --seed 0 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --transforms "identity" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

## ECG300
python main_finetune.py --seed 0 --c4_multiplier 3 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "longitudinal" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "longitudinal" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 1 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

python main_finetune.py --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "SelectedAug_20221025" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 1 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "SelectedAug_20221025" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 1 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 10 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --entity jspace --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "SelectedAug_20221025" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 1 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

python main_finetune.py --seed 0 --kernel_size 4 --c4_multiplier 4 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221025" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 1 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 10 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True


## 20230112 - PNTK - ECG300
python main_PNTK_supervised.py --n_classes 2 --patience 500 --seed 0 --mixup_alpha 0 --label_smoothing 0 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "identity" --encoder "clocs_cnn1d_functorch" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 16 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 100 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_PNTK_supervised.py --n_classes 2 --patience 500 --seed 0 --mixup_alpha 0 --label_smoothing 0 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "identity" --encoder "clocs_cnn1d_functorch" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 16 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 20 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.00001 --lr 0.00001 --weight_decay 5e-4 --batch_size 100 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

### Run for 10 epochs
python main_PNTK_supervised.py --n_classes 2 --patience 500 --seed 0 --mixup_alpha 0 --label_smoothing 0 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "identity" --encoder "clocs_cnn1d_functorch" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 16 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 10 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 100 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True



### Transformer 1D
python main_finetune.py --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --encoder "transformer1d" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --d_model 16 --use_raw_patch True --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --encoder "transformer1d" --ecg_resampling_length_target 256 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --encoder "transformer1d" --ecg_resampling_length_target 256 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True


## ECG300 + CVP
python main_finetune.py --seed 0 --in_channels 2 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "SelectedAug_20221025" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 1 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201_with_CVP" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --in_channels_type "ECG,CVP" --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "SelectedAug_20221025" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 1 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201_with_CVP" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --in_channels_type "CVP" --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --c4_multiplier 3 --transforms "SelectedAug_20221025" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 1 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201_with_CVP" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

# Linux
python main_finetune.py --seed 0 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "ddp" --gpus 0 --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 4 --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "ddp" --gpus 0 --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --seed 0 --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 4 --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "ddp" --gpus 0,1,2,3 --train_backbone True --read_data_by_chunk True --cluster_name "auto"


python main_finetune.py --seed 0 --save_eval_dataset True --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 4 --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "ddp" --gpus 0,1,2,3 --train_backbone True --read_data_by_chunk True --cluster_name "auto"
python main_finetune.py --seed 0 --save_eval_dataset True --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 4 --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "ddp" --gpus 0 --train_backbone True --read_data_by_chunk True --cluster_name "auto"


python main_finetune.py --seed 0 --in_channels_type "ECG,CVP" --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "gaussian" --encoder "clocs_cnn1d" --ecg_resampling_length_target 2500 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 4 --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "ddp" --gpus 0 --train_backbone True --read_data_by_chunk True --cluster_name "auto"

# MacOS + pretrained_mask
python main_finetune.py --seed 0 --encoder "resnet1d" --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "finetune_resnet18_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --mask_feature_extractor "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models/simclr_adios_1d/fqbfkouz" --ckpt_epoch 0 --read_data_by_chunk False --debug True

### TS Transformer 1D
python main_finetune.py --feat_dim 1 --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --pos_encoding "learned" --activation "gelu" --norm "BatchNorm" --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --encoder "ts_transformer1d" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --feat_dim 1 --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --pos_encoding "learned" --activation "gelu" --norm "BatchNorm" --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --encoder "ts_transformer1d" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 20 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

### ViT 1D
python main_finetune.py --encoder "vit_1D" --patch_size 15 --embedding_dim 256 --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --encoder "vit_1D" --patch_size 15 --embedding_dim 256 --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 20 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

# PatchTST 20230227
python main_finetune.py --encoder "patchTST" --task_name "classification" --patch_size 15 --stride 20 --embedding_dim 1 --output_attention False  --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --encoder "patchTST" --task_name "classification" --patch_size 15 --stride 20 --embedding_dim 256 --output_attention False  --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 20 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --encoder "patchTST" --task_name "classification" --patch_size 15 --stride 20 --embedding_dim 256 --output_attention False  --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --seed 0 --mixup_alpha 0 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "identity" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 20 --precision 32 --optimizer adam --scheduler warmup_cosine --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --encoder "patchTST" --task_name "classification" --patch_size 15 --stride 20 --embedding_dim 256 --output_attention False  --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --seed 0 --mixup_alpha 0 --label_smoothing 0 --wandb_dir "wandb_test" --transforms "identity" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 20 --precision 32 --optimizer adam --scheduler warmup_cosine --lr 0.000001 --weight_decay 0 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --encoder "patchTST" --task_name "classification" --patch_size 15 --stride 20 --embedding_dim 256 --output_attention False  --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 1650 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --encoder "patchTST" --task_name "classification" --patch_size 15 --stride 20 --embedding_dim 256 --output_attention False  --d_model 16 --nhead 1 --num_layers 8 --dim_feedforward 128 --dropout 0.1 --seed 0 --mixup_alpha 0.2 --label_smoothing 0.2 --wandb_dir "wandb_test" --transforms "SelectedAug_20221029" --ecg_resampling_length_target 300 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 20 --precision 32 --optimizer adam --scheduler warmup_cosine --classifier_lr 0.001 --lr 0.001 --weight_decay 5e-4 --batch_size 1650 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

# ClocsCNN + SAT 20230313
python main_finetune.py --loss_type "sat" --sat_momentum 0.8 --sat_pretrain 2 --dropout 0.1 --mixup_alpha 0 --label_smoothing 0 --seed 0 --c4_multiplier 3 --transforms "SelectedAug_20221029" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer adam --scheduler warmup_cosine --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True
python main_finetune.py --loss_type "sat" --sat_momentum 0.8 --sat_pretrain 2 --dropout 0.1 --mixup_alpha 0 --label_smoothing 0 --seed 0 --c4_multiplier 3 --transforms "SelectedAug_20221029" --encoder "clocs_cnn1d" --ecg_resampling_length_target 300 --stride 2 --embedding_dim 64 --normalize_signal True --dataset "ecg-TCH-40_patient-20220201" --data_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/data" --max_epochs 2 --precision 32 --optimizer sgd --scheduler warmup_cosine --lr 0.001 --weight_decay 5e-4 --batch_size 256 --num_workers 0 --checkpoint_dir "/Users/yj31/Dropbox/My Mac (C02FR2BBMD6T)/Documents/GitHub/adios/trained_models"  --project "adios_ecg_debug" --entity "yilongju" --name "supervised_clocs_ECG_debug" --wandb True --ptl_accelerator "cpu" --train_backbone True --read_data_by_chunk False --debug True

